/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pi2.views.ui.venda;

import br.com.pi2.exceptions.VendasException;
import br.com.pi2.model.jopos.Cliente;
import br.com.pi2.model.jopos.ItemVenda;
import br.com.pi2.model.jopos.Produto;
import br.com.pi2.model.jopos.Venda;
import br.com.pi2.service.ServicoCliente;
import br.com.pi2.service.ServicoProduto;
import br.com.pi2.service.ServicoVenda;
import br.com.pi2.views.ui.cliente.EditarCliente;
import br.com.pi2.views.ui.cliente.PesquisarCliente;
import br.com.pi2.views.ui.produto.PesquisarProduto;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matheus.jmaia
 */
public class TelaVendasUI extends javax.swing.JInternalFrame {

    Venda venda = new Venda();
    List<ItemVenda> ListaItems = new ArrayList<ItemVenda>();
    double totalVenda = 0.0;
    boolean resultSearch = false;

    public TelaVendasUI() {
        initComponents();
    }

    public boolean refreshList() throws VendasException, Exception {

        DefaultTableModel model = (DefaultTableModel) TabelaItemVenda.getModel();
        model.setRowCount(0);
        if (ListaItems == null || ListaItems.size() <= 0) {
            return false;
        }
        for (int i = 0; i < ListaItems.size(); i++) {
            ItemVenda item = ListaItems.get(i);
            if (item != null) {
                Object[] row = new Object[5];
                row[0] = item.getItemProduto().getCodigoProduto();
                row[1] = item.getItemProduto().getDescricao();
                row[2] = item.getItemProduto().getValor();
                row[3] = item.getQtde();
                row[4] = item.getPreco();
                model.addRow(row);
            }
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label1 = new javax.swing.JLabel();
        fieldCodProduto = new javax.swing.JTextField();
        botaoAdicionarProduto = new javax.swing.JButton();
        botaoBuscarProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldQtdProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaItemVenda = new javax.swing.JTable();
        label2 = new javax.swing.JLabel();
        labelValorTotal = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        fieldIDCliente = new javax.swing.JTextField();
        botatoAddCliente = new javax.swing.JButton();
        botaoBuscarCliente = new javax.swing.JButton();
        BotaoFinalizarVenda = new javax.swing.JButton();
        botaoCancelarVenda = new javax.swing.JButton();
        labelClienteADD = new javax.swing.JLabel();

        setTitle("Nova Venda");

        Label1.setText("Código do produto: ");

        fieldCodProduto.setToolTipText("Código do produto");
        fieldCodProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCodProdutoActionPerformed(evt);
            }
        });

        botaoAdicionarProduto.setText("Adicionar");
        botaoAdicionarProduto.setToolTipText("Adiciona o produto ao carrinho");
        botaoAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarProdutoActionPerformed(evt);
            }
        });

        botaoBuscarProduto.setText("Pesquisar produto");
        botaoBuscarProduto.setToolTipText("Busca determinado produto e seu código");
        botaoBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarProdutoActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade:");
        jLabel1.setToolTipText("");

        fieldQtdProduto.setToolTipText("Especifica a quantidade de um produto, caso vazio a quantidade será um por padrão ");

        TabelaItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Qtde", "Valor UN", "Valor Item"
            }
        ));
        jScrollPane1.setViewportView(TabelaItemVenda);

        label2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        label2.setText("Valor Total: R$");

        labelValorTotal.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelValorTotal.setText("0.0");

        label4.setText("ID do cliente:");

        fieldIDCliente.setToolTipText("Código do produto");
        fieldIDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIDClienteActionPerformed(evt);
            }
        });

        botatoAddCliente.setText("Adicionar cliente");
        botatoAddCliente.setToolTipText("Adiciona o cliente a venda");
        botatoAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botatoAddClienteActionPerformed(evt);
            }
        });

        botaoBuscarCliente.setText("Pesquisar cliente");
        botaoBuscarCliente.setToolTipText("Permite pesquisar um cliente por nome ou outros.");
        botaoBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarClienteActionPerformed(evt);
            }
        });

        BotaoFinalizarVenda.setText("Finalizar compra");
        BotaoFinalizarVenda.setToolTipText("Finaliza a venda");
        BotaoFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFinalizarVendaActionPerformed(evt);
            }
        });

        botaoCancelarVenda.setText("Cancelar");
        botaoCancelarVenda.setToolTipText("Cancela a compra");
        botaoCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarVendaActionPerformed(evt);
            }
        });

        labelClienteADD.setText("Cliente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCancelarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoFinalizarVenda)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelClienteADD)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoAdicionarProduto)
                                .addGap(188, 188, 188)
                                .addComponent(botaoBuscarProduto))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(label2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botatoAddCliente)
                                        .addGap(233, 233, 233)))
                                .addComponent(botaoBuscarCliente)))
                        .addGap(113, 113, 113))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label1)
                    .addComponent(fieldCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(fieldQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionarProduto)
                    .addComponent(botaoBuscarProduto))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4)
                    .addComponent(fieldIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botatoAddCliente)
                    .addComponent(botaoBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelClienteADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(labelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelarVenda)
                    .addComponent(BotaoFinalizarVenda))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarClienteActionPerformed
        PesquisarCliente pesquisarCliente = new PesquisarCliente();
        pesquisarCliente.dispose();
        pesquisarCliente = new PesquisarCliente();
        this.getParent().add(pesquisarCliente);
        this.openFrameInCenter(pesquisarCliente);
        pesquisarCliente.toFront();
    }//GEN-LAST:event_botaoBuscarClienteActionPerformed

    private void fieldIDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIDClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIDClienteActionPerformed

    private void botaoBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarProdutoActionPerformed
        PesquisarProduto pesquisarProduto = new PesquisarProduto();
        pesquisarProduto.dispose();
        pesquisarProduto = new PesquisarProduto();
        this.getParent().add(pesquisarProduto);
        this.openFrameInCenter(pesquisarProduto);
        pesquisarProduto.toFront();
    }//GEN-LAST:event_botaoBuscarProdutoActionPerformed
    
    public void openFrameInCenter(JInternalFrame jif) {
        Dimension desktopSize = this.getParent().getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    
    }
    private void botatoAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botatoAddClienteActionPerformed
        Cliente cliente = new Cliente();
        int id = Integer.parseInt(fieldIDCliente.getText());
        try {
            cliente = ServicoCliente.obter(id);
        } catch (Exception e) {

        }
        venda.setCliente(cliente);
        labelClienteADD.setText("Cliente vinculado: " + cliente.getNome() + "" + cliente.getSobrenome());
    }//GEN-LAST:event_botatoAddClienteActionPerformed

    private void botaoAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarProdutoActionPerformed
        Produto produto = new Produto();

        try {
            int cod = Integer.parseInt(fieldCodProduto.getText());
            produto = ServicoProduto.obterProduto(cod);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ItemVenda itemvenda = new ItemVenda();
        itemvenda.setItemProduto(produto);
        if (fieldQtdProduto.getText() == null || fieldQtdProduto.getText().equals("")) {
            itemvenda.setQtde(1);
            itemvenda.calcularPreco();
        } else {
            double qtd = Double.parseDouble(fieldQtdProduto.getText());
            itemvenda.setQtde(qtd);
            itemvenda.calcularPreco();
        }

        try {
            ListaItems.add(itemvenda);
        } catch (Exception e) {

        }

        try {
            resultSearch = refreshList();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                    "Falha ao adicionar item", JOptionPane.ERROR_MESSAGE);
            return;
        }

        totalVenda = totalVenda + itemvenda.getPreco();
        labelValorTotal.setText("" + totalVenda);


    }//GEN-LAST:event_botaoAdicionarProdutoActionPerformed

    private void fieldCodProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCodProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCodProdutoActionPerformed

    private void BotaoFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFinalizarVendaActionPerformed
        venda.setItemVenda(ListaItems);
        venda.setValor(totalVenda);
        try {
            ServicoVenda.adicionarVenda(venda);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Não é possível "
                    + "concluir a venda ",
                    "erro ao finalizar", JOptionPane.ERROR_MESSAGE);
        }
        JOptionPane.showMessageDialog(rootPane, "Venda Concluida!");

    }//GEN-LAST:event_BotaoFinalizarVendaActionPerformed

    private void botaoCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarVendaActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCancelarVendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoFinalizarVenda;
    private javax.swing.JLabel Label1;
    private javax.swing.JTable TabelaItemVenda;
    private javax.swing.JButton botaoAdicionarProduto;
    private javax.swing.JButton botaoBuscarCliente;
    private javax.swing.JButton botaoBuscarProduto;
    private javax.swing.JButton botaoCancelarVenda;
    private javax.swing.JButton botatoAddCliente;
    private javax.swing.JTextField fieldCodProduto;
    private javax.swing.JTextField fieldIDCliente;
    private javax.swing.JTextField fieldQtdProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel labelClienteADD;
    private javax.swing.JLabel labelValorTotal;
    // End of variables declaration//GEN-END:variables
}
